//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IHistoryRepository : SkyWeb.DatVM.Data.IBaseRepository<History>
    {
    }
    
    public partial class HistoryRepository : SkyWeb.DatVM.Data.BaseRepository<History>, IHistoryRepository
    {
    	public HistoryRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
