//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProduct_positionRepository : SkyWeb.DatVM.Data.IBaseRepository<Product_position>
    {
    }
    
    public partial class Product_positionRepository : SkyWeb.DatVM.Data.BaseRepository<Product_position>, IProduct_positionRepository
    {
    	public Product_positionRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
