//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CornerViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Corner>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual double Latitude { get; set; }
    			public virtual double Longitude { get; set; }
    			public virtual int MapId { get; set; }
    			public virtual int Floor { get; set; }
    			public virtual int Position { get; set; }
    			public virtual string Description { get; set; }
    	
    	public CornerViewModel() : base() { }
    	public CornerViewModel(CapstoneData.Models.Entities.Corner entity) : base(entity) { }
    
    }
}
