//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Device>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MACAddress { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int UserId { get; set; }
    	
    	public DeviceViewModel() : base() { }
    	public DeviceViewModel(CapstoneData.Models.Entities.Device entity) : base(entity) { }
    
    }
}
