//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.History>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual System.DateTime CreatedDate { get; set; }
    			public virtual int UserId { get; set; }
    			public virtual int TypeId { get; set; }
    	
    	public HistoryViewModel() : base() { }
    	public HistoryViewModel(CapstoneData.Models.Entities.History entity) : base(entity) { }
    
    }
}
