//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseTypeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.LicenseType>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string TypeName { get; set; }
    			public virtual Nullable<int> BuyDate { get; set; }
    			public virtual Nullable<double> Price { get; set; }
    			public virtual Nullable<int> PackageId { get; set; }
    	
    	public LicenseTypeViewModel() : base() { }
    	public LicenseTypeViewModel(CapstoneData.Models.Entities.LicenseType entity) : base(entity) { }
    
    }
}
