//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Map>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int BuildingId { get; set; }
    			public virtual string MapUrl { get; set; }
    			public virtual int Floor { get; set; }
    			public virtual Nullable<double> Altitude { get; set; }
    	
    	public MapViewModel() : base() { }
    	public MapViewModel(CapstoneData.Models.Entities.Map entity) : base(entity) { }
    
    }
}
