//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkerViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Marker>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<double> Longitude { get; set; }
    			public virtual Nullable<double> Latitude { get; set; }
    			public virtual Nullable<double> Altitude { get; set; }
    			public virtual Nullable<int> MapId { get; set; }
    	
    	public MarkerViewModel() : base() { }
    	public MarkerViewModel(CapstoneData.Models.Entities.Marker entity) : base(entity) { }
    
    }
}
