//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageLicenseViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.PackageLicense>
    {
    	
    			public virtual int PackageId { get; set; }
    			public virtual string Name { get; set; }
    	
    	public PackageLicenseViewModel() : base() { }
    	public PackageLicenseViewModel(CapstoneData.Models.Entities.PackageLicense entity) : base(entity) { }
    
    }
}
