//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_positionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Product_position>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<double> Latitude { get; set; }
    			public virtual Nullable<double> Longitude { get; set; }
    			public virtual Nullable<double> Altitude { get; set; }
    			public virtual string DeviceId { get; set; }
    			public virtual System.DateTime CreatedDate { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public Product_positionViewModel() : base() { }
    	public Product_positionViewModel(CapstoneData.Models.Entities.Product_position entity) : base(entity) { }
    
    }
}
