//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_positionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<CapstoneData.Models.Entities.Product_position>
    {
    	
    			public virtual int id { get; set; }
    			public virtual Nullable<double> latitude { get; set; }
    			public virtual Nullable<double> longitude { get; set; }
    			public virtual Nullable<double> altitude { get; set; }
    			public virtual string deviceId { get; set; }
    	
    	public Product_positionViewModel() : base() { }
    	public Product_positionViewModel(CapstoneData.Models.Entities.Product_position entity) : base(entity) { }
    
    }
}
