//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBuildingService : SkyWeb.DatVM.Data.IBaseService<Building>
    {
    }
    
    public partial class BuildingService : SkyWeb.DatVM.Data.BaseService<Building>, IBuildingService
    {
        public BuildingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IBuildingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
