//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IDistrictService : SkyWeb.DatVM.Data.IBaseService<District>
    {
    }
    
    public partial class DistrictService : SkyWeb.DatVM.Data.BaseService<District>, IDistrictService
    {
        public DistrictService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IDistrictRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
