//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILicenseTypeService : SkyWeb.DatVM.Data.IBaseService<LicenseType>
    {
    }
    
    public partial class LicenseTypeService : SkyWeb.DatVM.Data.BaseService<LicenseType>, ILicenseTypeService
    {
        public LicenseTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILicenseTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
