//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILicienseService : SkyWeb.DatVM.Data.IBaseService<Liciense>
    {
    }
    
    public partial class LicienseService : SkyWeb.DatVM.Data.BaseService<Liciense>, ILicienseService
    {
        public LicienseService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILicienseRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
