//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMapService : SkyWeb.DatVM.Data.IBaseService<Map>
    {
    }
    
    public partial class MapService : SkyWeb.DatVM.Data.BaseService<Map>, IMapService
    {
        public MapService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMapRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
