//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPackageLicenseService : SkyWeb.DatVM.Data.IBaseService<PackageLicense>
    {
    }
    
    public partial class PackageLicenseService : SkyWeb.DatVM.Data.BaseService<PackageLicense>, IPackageLicenseService
    {
        public PackageLicenseService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPackageLicenseRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
