//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProvinceService : SkyWeb.DatVM.Data.IBaseService<Province>
    {
    }
    
    public partial class ProvinceService : SkyWeb.DatVM.Data.BaseService<Province>, IProvinceService
    {
        public ProvinceService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProvinceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
