//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corner
    {
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int MapId { get; set; }
        public int Floor { get; set; }
        public int Position { get; set; }
        public string Desciption { get; set; }
    
        public virtual Map Map { get; set; }
    }
}
