//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public int BuyDate { get; set; }
        public double Price { get; set; }
    
        public virtual User User { get; set; }
    }
}
