//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liciense
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DayOfPurchase { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int Type { get; set; }
        public bool IsUse { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
