//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        public int Id { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<int> MapId { get; set; }
    
        public virtual Map Map { get; set; }
    }
}
