//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneData.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Floor { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public int MapId { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> PosAX { get; set; }
        public Nullable<int> PosAY { get; set; }
        public Nullable<int> PosBX { get; set; }
        public Nullable<int> PosBY { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Map Map { get; set; }
    }
}
