//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisky.ResourcesLanguage.MenuText", typeof(MenuText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This advertising is now running.
        /// </summary>
        public static string AcceptSuccess {
            get {
                return ResourceManager.GetString("AcceptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string AccessPoints {
            get {
                return ResourceManager.GetString("AccessPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an error in process, please try again.
        /// </summary>
        public static string ActionError {
            get {
                return ResourceManager.GetString("ActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising Infomation.
        /// </summary>
        public static string AdvertisingInfomation {
            get {
                return ResourceManager.GetString("AdvertisingInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising overview.
        /// </summary>
        public static string Advertisingoverview {
            get {
                return ResourceManager.GetString("Advertisingoverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising report chart.
        /// </summary>
        public static string AdvertisingReportChart {
            get {
                return ResourceManager.GetString("AdvertisingReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string Advertisings {
            get {
                return ResourceManager.GetString("Advertisings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Report Chart.
        /// </summary>
        public static string BrowserReportChart {
            get {
                return ResourceManager.GetString("BrowserReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Information.
        /// </summary>
        public static string ConfigInfo {
            get {
                return ResourceManager.GetString("ConfigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Landing Page.
        /// </summary>
        public static string CreateLandingPage {
            get {
                return ResourceManager.GetString("CreateLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTR.
        /// </summary>
        public static string CTR {
            get {
                return ResourceManager.GetString("CTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custome filter.
        /// </summary>
        public static string CustomeFilter {
            get {
                return ResourceManager.GetString("CustomeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device info.
        /// </summary>
        public static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Report Chart.
        /// </summary>
        public static string DeviceReportChart {
            get {
                return ResourceManager.GetString("DeviceReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to device.
        /// </summary>
        public static string GoToManageAccessPoint {
            get {
                return ResourceManager.GetString("GoToManageAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to advertising.
        /// </summary>
        public static string GoToManageAdvertising {
            get {
                return ResourceManager.GetString("GoToManageAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to location.
        /// </summary>
        public static string GoToManageLocation {
            get {
                return ResourceManager.GetString("GoToManageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        public static string Insights {
            get {
                return ResourceManager.GetString("Insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string InteractionPage {
            get {
                return ResourceManager.GetString("InteractionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Landing Page is current in use for another Landing Page.
        /// </summary>
        public static string IsSkippingLandingPage {
            get {
                return ResourceManager.GetString("IsSkippingLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        public static string LandingPage {
            get {
                return ResourceManager.GetString("LandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Layout.
        /// </summary>
        public static string LayoutManagement {
            get {
                return ResourceManager.GetString("LayoutManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Clickthrough.
        /// </summary>
        public static string LoginByClickThrough {
            get {
                return ResourceManager.GetString("LoginByClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Facebook.
        /// </summary>
        public static string LoginByFaceBook {
            get {
                return ResourceManager.GetString("LoginByFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Google+.
        /// </summary>
        public static string LoginByGoogle {
            get {
                return ResourceManager.GetString("LoginByGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Laptop.
        /// </summary>
        public static string LoginByLaptop {
            get {
                return ResourceManager.GetString("LoginByLaptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Infomation.
        /// </summary>
        public static string LoginInfomation {
            get {
                return ResourceManager.GetString("LoginInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Overview.
        /// </summary>
        public static string LoginOverview {
            get {
                return ResourceManager.GetString("LoginOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login report.
        /// </summary>
        public static string LoginReport {
            get {
                return ResourceManager.GetString("LoginReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login report chart.
        /// </summary>
        public static string LoginReportChart {
            get {
                return ResourceManager.GetString("LoginReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Session.
        /// </summary>
        public static string LoginSession {
            get {
                return ResourceManager.GetString("LoginSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success Rate.
        /// </summary>
        public static string LoginSuccessRate {
            get {
                return ResourceManager.GetString("LoginSuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Type.
        /// </summary>
        public static string LoginTp {
            get {
                return ResourceManager.GetString("LoginTp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string ManageAccessPoint {
            get {
                return ResourceManager.GetString("ManageAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage access point.
        /// </summary>
        public static string ManageAccessPoints {
            get {
                return ResourceManager.GetString("ManageAccessPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point activity.
        /// </summary>
        public static string ManageAPAtivity {
            get {
                return ResourceManager.GetString("ManageAPAtivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage app.
        /// </summary>
        public static string ManageApp {
            get {
                return ResourceManager.GetString("ManageApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage category image.
        /// </summary>
        public static string ManageCategoryImage {
            get {
                return ResourceManager.GetString("ManageCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage landing template.
        /// </summary>
        public static string ManageLandingTemplate {
            get {
                return ResourceManager.GetString("ManageLandingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ManageLocations {
            get {
                return ResourceManager.GetString("ManageLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage publisher.
        /// </summary>
        public static string ManagePublisher {
            get {
                return ResourceManager.GetString("ManagePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user accounts.
        /// </summary>
        public static string ManageUserAccounts {
            get {
                return ResourceManager.GetString("ManageUserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Guest.
        /// </summary>
        public static string NewGuest {
            get {
                return ResourceManager.GetString("NewGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Users.
        /// </summary>
        public static string NewUsers {
            get {
                return ResourceManager.GetString("NewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visit.
        /// </summary>
        public static string NewVisit {
            get {
                return ResourceManager.GetString("NewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        public static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Report Chart.
        /// </summary>
        public static string OSReportChart {
            get {
                return ResourceManager.GetString("OSReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Overview.
        /// </summary>
        public static string PersonOverview {
            get {
                return ResourceManager.GetString("PersonOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string Presence {
            get {
                return ResourceManager.GetString("Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string PresenceAnalysis {
            get {
                return ResourceManager.GetString("PresenceAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview wifi.
        /// </summary>
        public static string PreviewWifi {
            get {
                return ResourceManager.GetString("PreviewWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate (%).
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        public static string Reach {
            get {
                return ResourceManager.GetString("Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Customers.
        /// </summary>
        public static string RecentCustomers {
            get {
                return ResourceManager.GetString("RecentCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Guest.
        /// </summary>
        public static string ReturnGuest {
            get {
                return ResourceManager.GetString("ReturnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visit.
        /// </summary>
        public static string ReturnVisit {
            get {
                return ResourceManager.GetString("ReturnVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session / Guest Rate.
        /// </summary>
        public static string SessionPerGuestRate {
            get {
                return ResourceManager.GetString("SessionPerGuestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total click.
        /// </summary>
        public static string TotalClick {
            get {
                return ResourceManager.GetString("TotalClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Guest.
        /// </summary>
        public static string TotalGuest {
            get {
                return ResourceManager.GetString("TotalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total login.
        /// </summary>
        public static string TotalLogin {
            get {
                return ResourceManager.GetString("TotalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total login success.
        /// </summary>
        public static string TotalLoginSuccess {
            get {
                return ResourceManager.GetString("TotalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total View.
        /// </summary>
        public static string TotalView {
            get {
                return ResourceManager.GetString("TotalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visit.
        /// </summary>
        public static string TotalVisit {
            get {
                return ResourceManager.GetString("TotalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Gender.
        /// </summary>
        public static string UnknowGender {
            get {
                return ResourceManager.GetString("UnknowGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by other Social Account.
        /// </summary>
        public static string UnknowSocial {
            get {
                return ResourceManager.GetString("UnknowSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User behaviour.
        /// </summary>
        public static string UserBehaviour {
            get {
                return ResourceManager.GetString("UserBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Charactertistic.
        /// </summary>
        public static string UserCharactertistic {
            get {
                return ResourceManager.GetString("UserCharactertistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Flow.
        /// </summary>
        public static string UserFlow {
            get {
                return ResourceManager.GetString("UserFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User overview.
        /// </summary>
        public static string UserOverview {
            get {
                return ResourceManager.GetString("UserOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserStatistic {
            get {
                return ResourceManager.GetString("UserStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User visit.
        /// </summary>
        public static string UserVisit {
            get {
                return ResourceManager.GetString("UserVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit By Day.
        /// </summary>
        public static string VisitByDay {
            get {
                return ResourceManager.GetString("VisitByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit By Time Slot.
        /// </summary>
        public static string VisitByTimeSlot {
            get {
                return ResourceManager.GetString("VisitByTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Overview.
        /// </summary>
        public static string VisitOverview {
            get {
                return ResourceManager.GetString("VisitOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Makerting Solution.
        /// </summary>
        public static string WifiMakertingSolution {
            get {
                return ResourceManager.GetString("WifiMakertingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi media.
        /// </summary>
        public static string WifiMedia {
            get {
                return ResourceManager.GetString("WifiMedia", resourceCulture);
            }
        }
    }
}
